/**
 * Conformance of the Lean model's JavaScript string layer with the real engine.
 *
 * `verification/lean/SomaVerify/Support/JsString.lean` models the parts of JS
 * string semantics that module models build on: `.length` in UTF-16 code units,
 * `.trim()` with ECMAScript's white-space set, and `.startsWith()`. Every proof
 * about a module model inherits that layer, so it is tested rather than trusted:
 * `SomaVerify/JsString/Vectors.lean` records what the model returns for each
 * call, and this suite asks the engine the same questions. The vector domain is
 * every string of length 0..3 over an alphabet chosen for the edges, a sweep of
 * single code points (all ECMAScript white space, the usual false friends such
 * as U+0085, and non-ASCII letters), and every prefix pair over an alphabet with
 * two astral characters that share a UTF-16 high surrogate.
 *
 * The vector file is regenerated and drift-checked by the "Lean Verify"
 * workflow (`scripts/verification/lean-verify.sh --check`), so it cannot fall
 * behind the model unnoticed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = path.resolve(__dirname, '../../..');

type Result = number | string | boolean;

interface Call {
  fn: string;
  args: string[];
  expect: Result;
}

interface VectorFile {
  module: string;
  generator: string;
  lean: string;
  count: number;
  cases: Call[];
}

interface EngineCall {
  arity: number;
  run: (args: string[]) => Result;
}

/** What the engine itself answers, per vector `fn`. */
const ENGINE = new Map<string, EngineCall>([
  ['length', { arity: 1, run: ([s]) => s.length }],
  ['trim', { arity: 1, run: ([s]) => s.trim() }],
  ['startsWith', { arity: 2, run: ([s, search]) => s.startsWith(search) }],
]);

const vectors = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'verification/vectors/js-string.json'), 'utf8'),
) as VectorFile;

function hex(codePoint: number): string {
  return `U+${codePoint.toString(16).toUpperCase().padStart(4, '0')}`;
}

/** The interesting characters are invisible, so failures name code points. */
function codePoints(text: string): string {
  if (text.length === 0) return '(empty)';
  return Array.from(text, (ch) => hex(ch.codePointAt(0) ?? 0)).join(' ');
}

describe('js-string Lean conformance vectors', () => {
  it('carry exactly the calls they declare, each well-formed and none repeated', () => {
    expect(vectors.module).toBe('js-string');
    expect(vectors.count).toBe(vectors.cases.length);
    expect(vectors.count).toBeGreaterThan(100);

    const malformed = vectors.cases.filter(
      (c) =>
        !Array.isArray(c.args) ||
        c.args.length !== ENGINE.get(c.fn)?.arity ||
        !c.args.every((arg) => typeof arg === 'string'),
    );
    expect(malformed).toEqual([]);

    // A repeated call would inflate the count without adding coverage.
    expect(new Set(vectors.cases.map((c) => JSON.stringify([c.fn, c.args]))).size).toBe(vectors.count);
  });

  it('were generated by the pinned Lean toolchain', () => {
    const toolchain = fs.readFileSync(path.join(repoRoot, 'verification/lean/lean-toolchain'), 'utf8').trim();
    expect(toolchain).toBe(`leanprover/lean4:v${vectors.lean}`);
  });

  for (const [fn, engine] of ENGINE) {
    it(`agree with String.prototype.${fn} on every case`, () => {
      const cases = vectors.cases.filter((c) => c.fn === fn);
      expect(cases.length, `vector cases for ${fn}`).toBeGreaterThan(100);
      const mismatches = cases
        .map((c) => ({ c, actual: engine.run(c.args) }))
        .filter(({ c, actual }) => actual !== c.expect)
        .map(({ c, actual }) => {
          const show = (value: Result) => (typeof value === 'string' ? `[${codePoints(value)}]` : String(value));
          return `${fn}(${c.args.map((arg) => `[${codePoints(arg)}]`).join(', ')}): engine ${show(actual)}, model ${show(c.expect)}`;
        });
      expect(mismatches).toEqual([]);
    });
  }

  it('cover every code point the engine treats as white space', () => {
    // Agreement is only as strong as the domain. The model's set is proved to be
    // exactly its 25-entry table (`jsIsWhitespace_iff`), and the sweep puts every
    // table entry in the vectors; this scan closes the other direction, so a code
    // point this engine trims but the table lacks cannot hide outside the domain.
    const singles = new Set(
      vectors.cases
        .filter((c) => c.fn === 'trim' && Array.from(c.args[0]).length === 1)
        .map((c) => c.args[0].codePointAt(0)),
    );
    const missing: string[] = [];
    for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
      if (codePoint >= 0xd800 && codePoint <= 0xdfff) continue;
      if (String.fromCodePoint(codePoint).trim() === '' && !singles.has(codePoint)) missing.push(hex(codePoint));
    }
    expect(missing).toEqual([]);
  });
});
