/**
 * Conformance of the Lean model's JavaScript string layer with the real engine.
 *
 * `verification/lean/SomaVerify/Support/JsString.lean` models the parts of JS
 * string semantics that module models build on: `.length` in UTF-16 code units
 * and `.trim()` with ECMAScript's white-space set. Every proof about a module
 * model inherits that layer, so it is tested rather than trusted:
 * `SomaVerify/JsString/Vectors.lean` enumerates every string of length 0..3
 * over an alphabet chosen for the edges (ASCII and Unicode white space, a line
 * separator, a BOM, a character outside the BMP) and records what the model
 * says; this suite asks the engine the same questions.
 *
 * The vector file is regenerated and drift-checked by the "Lean Verify"
 * workflow (`scripts/verification/lean-verify.sh --check`), so it cannot fall
 * behind the model unnoticed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = path.resolve(__dirname, '../../..');

interface JsStringCase {
  input: string;
  expect: { length: number; trim: string };
}

interface VectorFile {
  module: string;
  generator: string;
  lean: string;
  count: number;
  cases: JsStringCase[];
}

const vectors = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'verification/vectors/js-string.json'), 'utf8'),
) as VectorFile;

/** The interesting characters are invisible, so failures name code points. */
function codePoints(text: string): string {
  if (text.length === 0) return '(empty)';
  return Array.from(text, (ch) => `U+${(ch.codePointAt(0) ?? 0).toString(16).toUpperCase().padStart(4, '0')}`).join(
    ' ',
  );
}

describe('js-string Lean conformance vectors', () => {
  it('carry exactly the cases they declare, enough of them, and no duplicates', () => {
    expect(vectors.module).toBe('js-string');
    expect(vectors.count).toBe(vectors.cases.length);
    expect(vectors.count).toBeGreaterThan(100);
    // A repeated input would inflate the count without adding coverage.
    expect(new Set(vectors.cases.map((c) => c.input)).size).toBe(vectors.count);
  });

  it('were generated by the pinned Lean toolchain', () => {
    const toolchain = fs.readFileSync(path.join(repoRoot, 'verification/lean/lean-toolchain'), 'utf8').trim();
    expect(toolchain).toBe(`leanprover/lean4:v${vectors.lean}`);
  });

  it('agree with String.prototype.length on every case', () => {
    const mismatches = vectors.cases
      .filter((c) => c.input.length !== c.expect.length)
      .map((c) => `[${codePoints(c.input)}] engine ${c.input.length}, model ${c.expect.length}`);
    expect(mismatches).toEqual([]);
  });

  it('agree with String.prototype.trim on every case', () => {
    const mismatches = vectors.cases
      .filter((c) => c.input.trim() !== c.expect.trim)
      .map(
        (c) => `[${codePoints(c.input)}] engine [${codePoints(c.input.trim())}], model [${codePoints(c.expect.trim)}]`,
      );
    expect(mismatches).toEqual([]);
  });
});
