/**
 * SSOT user-instructions block builder.
 *
 * Rendered into the system prompt once per `buildSystemPrompt()` call and
 * cached on `session.systemPrompt`. Designed to keep prompt cache hits when
 * the SSOT is unchanged:
 *   - `active` + `todo` entries render in full (original text).
 *   - `completed` entries render verbatim when there is only one, and collapse
 *     into a pre-computed summary when there are two or more (summary is
 *     generated by `src/conversation/instructions-summarizer.ts`).
 *
 * The block is `<user-instructions-ssot>…</user-instructions-ssot>` so the
 * model can easily locate it alongside other structured blocks
 * (`<persona>`, `<channel-description>`, etc).
 */

import { createHash } from 'node:crypto';
import type { ConversationSession, SessionInstruction } from '../types';

export const USER_INSTRUCTIONS_BLOCK_OPEN = '<user-instructions-ssot>';
export const USER_INSTRUCTIONS_BLOCK_CLOSE = '</user-instructions-ssot>';

/**
 * Deterministic hash over the `completed` subset of `instructions`. Used to
 * detect whether `session.instructionsCompletedSummary` is stale relative to
 * the current completed entries.
 *
 * We hash `id|completedAt` (not `text`) because:
 *   1. The id is globally unique per instruction — covers add/remove/reorder.
 *   2. `completedAt` changes whenever an entry flips from `active`/`todo` to
 *      `completed`, which is precisely when a resummary is needed. Text
 *      editing without a status change is rare and intentionally ignored
 *      (would fire summaries for trivial wording churn).
 */
export function computeCompletedUpstreamHash(instructions: SessionInstruction[] | undefined): string {
  const completed = (instructions || [])
    .filter((i) => i.status === 'completed')
    .map((i) => `${i.id}|${i.completedAt ?? 0}`)
    .sort(); // Deterministic regardless of array order (defensive).
  const payload = completed.join('\n');
  return createHash('sha1').update(payload).digest('hex');
}

function renderBullet(i: SessionInstruction): string {
  // Collapse internal whitespace but preserve the user's text verbatim otherwise.
  const text = i.text.replace(/\s+/g, ' ').trim();
  return `- ${text}`;
}

/**
 * Build the `<user-instructions-ssot>` block. Returns an empty string when
 * there are no instructions — the caller should not emit the opening tag in
 * that case (keeps prompt noise-free for fresh sessions).
 *
 * PR1 scope (#754) is mechanical sealed-enum compatibility only. The
 * builder must read the new `'cancelled'` status without crashing — but
 * MUST NOT render cancelled instructions into the prompt. Surfacing
 * cancelled state to the model is a prompt-block design decision that
 * belongs in #756.
 *
 * TODO(#756): expose cancelled instructions in prompt block.
 */
export function buildUserInstructionsBlock(session: ConversationSession | undefined): string {
  const instructions = session?.instructions || [];
  if (instructions.length === 0) return '';

  // Sealed status set (#754): active | completed | cancelled. Legacy 'todo'
  // is migrated to 'active' before reaching this builder. Cancelled entries
  // are READ (no crash) but DROPPED from the rendered prompt — see
  // TODO(#756) above.
  const active: SessionInstruction[] = [];
  const completed: SessionInstruction[] = [];
  for (const i of instructions) {
    const s = i.status ?? 'active';
    if (s === 'completed') completed.push(i);
    else if (s === 'cancelled') {
      // Intentionally skipped in PR1 (#754). #756 owns cancelled-rendering.
      continue;
    } else active.push(i);
  }

  const sections: string[] = [];

  if (active.length > 0) {
    sections.push(['## Active', ...active.map(renderBullet)].join('\n'));
  }

  if (completed.length === 1) {
    // Single completed entry — render verbatim (cheaper than a summary).
    sections.push(['## Completed', renderBullet(completed[0])].join('\n'));
  } else if (completed.length >= 2) {
    const cached = session?.instructionsCompletedSummary;
    const expectedHash = computeCompletedUpstreamHash(instructions);
    const summary =
      cached && cached.upstreamHash === expectedHash && cached.summary.trim().length > 0
        ? cached.summary.trim()
        : `(summary pending for ${completed.length} completed entries…)`;
    sections.push(['## Completed', summary].join('\n'));
  }

  if (sections.length === 0) return '';

  return `${USER_INSTRUCTIONS_BLOCK_OPEN}\n${sections.join('\n\n')}\n${USER_INSTRUCTIONS_BLOCK_CLOSE}`;
}
