/**
 * Conformance of `src/sensitive-path-filter.ts` with its Lean model.
 *
 * `verification/lean/SomaVerify/SensitivePath/Model.lean` transcribes `checkSensitivePath` and
 * `checkSensitiveGlob` (with the `normalizePath` they share), `Proofs.lean` proves the model's
 * invariants, and `Vectors.lean` records the model's answer for every path and glob of a small
 * alphabet. This suite asks the real module the same questions.
 *
 * The model runs with a stand-in HOME that the vector file writes as `<HOME>`. Each case gets the
 * module's HOME in its place, computed as the module computes it when it loads (`os.homedir()`
 * resolved, with `/private/tmp` written `/tmp`); reasons are compared with that HOME written back
 * as `<HOME>`.
 *
 * The vector file is regenerated and drift-checked by the "Lean Verify" workflow
 * (`scripts/verification/lean-verify.sh --check`), so it cannot fall behind the model unnoticed.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';
import { normalizeTmpPath } from '../path-utils';
import { checkSensitiveGlob, checkSensitivePath, type SensitivePathResult } from '../sensitive-path-filter';

const repoRoot = path.resolve(__dirname, '../..');
const PLACEHOLDER = '<HOME>';
const HOME = normalizeTmpPath(path.resolve(os.homedir()));

interface Expected {
  isSensitive: boolean;
  reason: string | null;
}

/** `checkSensitivePath(path)`. */
interface PathCase extends Expected {
  path: string;
}

/** `checkSensitiveGlob(glob)`, or `checkSensitiveGlob(glob, basePath)` when `basePath` is a string. */
interface GlobCase extends Expected {
  glob: string;
  basePath: string | null;
}

type Case = PathCase | GlobCase;

interface VectorFile {
  module: string;
  generator: string;
  lean: string;
  count: number;
  cases: Case[];
}

const vectorText = fs.readFileSync(path.join(repoRoot, 'verification/vectors/sensitive-path.json'), 'utf8');
const vectors = JSON.parse(vectorText) as VectorFile;

function withHome(text: string): string {
  return text.split(PLACEHOLDER).join(HOME);
}

function withPlaceholder(text: string): string {
  return text.split(HOME).join(PLACEHOLDER);
}

function describeCase(c: Case): string {
  if ('path' in c) return `checkSensitivePath(${JSON.stringify(c.path)})`;
  const base = c.basePath === null ? '' : `, ${JSON.stringify(c.basePath)}`;
  return `checkSensitiveGlob(${JSON.stringify(c.glob)}${base})`;
}

function run(c: Case): SensitivePathResult {
  if ('path' in c) return checkSensitivePath(withHome(c.path));
  if (c.basePath === null) return checkSensitiveGlob(withHome(c.glob));
  return checkSensitiveGlob(withHome(c.glob), withHome(c.basePath));
}

describe('sensitive-path Lean conformance vectors', () => {
  it('carry exactly the cases they declare, enough of them, and no duplicates', () => {
    expect(vectors.module).toBe('sensitive-path');
    expect(vectors.count).toBe(vectors.cases.length);
    expect(vectors.count).toBeGreaterThan(200);
    // A repeated call would inflate the count without adding coverage.
    expect(new Set(vectors.cases.map(describeCase)).size).toBe(vectors.count);
  });

  it('were generated by the pinned Lean toolchain', () => {
    const toolchain = fs.readFileSync(path.join(repoRoot, 'verification/lean/lean-toolchain'), 'utf8').trim();
    expect(toolchain).toBe(`leanprover/lean4:v${vectors.lean}`);
  });

  it('run with a HOME that the vectors reach only through the placeholder', () => {
    // The model's stand-in HOME is one plain segment; the real one must be as regular:
    // absolute, not the root, and without empty, `.` or `..` segments.
    const homeSegments = HOME.split('/').slice(1);
    expect(HOME.startsWith('/')).toBe(true);
    expect(homeSegments.length).toBeGreaterThan(0);
    expect(homeSegments.filter((s) => s === '' || s === '.' || s === '..')).toEqual([]);
    // HOME is not sensitive, so no directory on the way to it is: the module's walk passes through
    // them, the model's single-segment HOME has none.
    expect(checkSensitivePath(HOME).isSensitive).toBe(false);
    // No path spelled from the alphabet may reach HOME without the placeholder (so at least one
    // HOME segment lies outside the alphabet), and no text in the file may contain HOME, or
    // writing HOME back as the placeholder would be ambiguous. The module compares names without
    // regard to case, so neither may in any case.
    const alphabet = new Set(
      vectors.cases
        .flatMap((c) => ('path' in c ? [c.path] : [c.glob, c.basePath ?? '']))
        .flatMap((p) => p.toLowerCase().split('/')),
    );
    expect(homeSegments.every((s) => alphabet.has(s.toLowerCase()))).toBe(false);
    expect(vectorText.toLowerCase().includes(HOME.toLowerCase())).toBe(false);
  });

  it('agree with checkSensitivePath and checkSensitiveGlob on every case', () => {
    const mismatches: string[] = [];
    for (const c of vectors.cases) {
      const actual = run(c);
      const reason = actual.reason === undefined ? null : withPlaceholder(actual.reason);
      if (actual.isSensitive !== c.isSensitive || reason !== c.reason) {
        mismatches.push(
          `${describeCase(c)}: module ${JSON.stringify({ isSensitive: actual.isSensitive, reason })}, ` +
            `model ${JSON.stringify({ isSensitive: c.isSensitive, reason: c.reason })}`,
        );
      }
    }
    expect(mismatches).toEqual([]);
  });
});
