#!/bin/bash
# Step 04: .env Configuration
# Assembles the .env file from collected secrets + additional config.

run_step() {
    step_header "04" ".env Configuration"

    if ! should_run_step "04" ".env configured"; then
        return 0
    fi

    local secrets_tmp="$REPO_DIR/.setup-secrets.tmp"

    # Collect remaining config
    local base_dir
    base_dir=$(ask_value "BASE_DIRECTORY (per-user working dirs)" "base_directory" "$HOME/Code")

    local debug
    debug=$(ask_choice "Debug mode:" "false (production)" "true (verbose logging)")
    [[ "$debug" == "true"* ]] && debug="true" || debug="false"
    set_state "debug" "$debug"

    # Optional: Anthropic API key
    local anthropic_key=""
    local existing_key=""
    if [[ -f "$REPO_DIR/.env" ]]; then
        existing_key=$(grep "^ANTHROPIC_API_KEY=" "$REPO_DIR/.env" 2>/dev/null | cut -d= -f2- || echo "")
    fi

    echo ""
    echo -e "${DIM}ANTHROPIC_API_KEY is only needed if you don't have a Claude Code subscription.${NC}"
    anthropic_key=$(ask_secret "ANTHROPIC_API_KEY (optional, Enter to skip)" "$(mask_secret "$existing_key" 8)")
    anthropic_key="${anthropic_key:-$existing_key}"

    # Assemble .env
    local env_file="$REPO_DIR/.env"
    {
        echo "# soma-work environment configuration"
        echo "# Generated by setup-wizard on $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""

        # Slack tokens from secrets tmp
        if [[ -f "$secrets_tmp" ]]; then
            grep "^SLACK_" "$secrets_tmp" 2>/dev/null || true
        fi

        echo ""
        echo "# Base directory for per-user working directories"
        echo "BASE_DIRECTORY=$base_dir"
        echo ""
        echo "# Debug mode"
        echo "DEBUG=$debug"

        # Anthropic key
        if [[ -n "$anthropic_key" ]]; then
            echo ""
            echo "# Claude API (only if no Claude Code subscription)"
            echo "ANTHROPIC_API_KEY=$anthropic_key"
        fi

        # GitHub integration
        echo ""
        if [[ -f "$secrets_tmp" ]]; then
            local has_github=false
            if grep -q "^GITHUB_" "$secrets_tmp" 2>/dev/null; then
                echo "# GitHub Integration"
                grep "^GITHUB_" "$secrets_tmp" 2>/dev/null || true
                has_github=true
            fi
        fi
    } > "$env_file"
    chmod 600 "$env_file"

    # Cleanup temp secrets
    rm -f "$secrets_tmp"

    success ".env written to $env_file"
    echo -e "  ${DIM}$(wc -l < "$env_file" | tr -d ' ') lines${NC}"

    mark_step_done "04"
    return 0
}
