/**
 * Conformance of `parseCli` with its Lean model.
 *
 * `verification/lean/SomaVerify/CliArgs/Model.lean` transcribes `src/cli/args.ts`,
 * and the theorems next to it (every token consumed exactly once, no flag
 * twice, every flag declared with its kind, `--profile` always a value flag,
 * the normalized sessions tail, stray positionals refused) are about that
 * model. This suite ties the model to the code: `SomaVerify/CliArgs/Vectors.lean`
 * records what the model's `parseCli` returns for every argv in
 * `verification/vectors/cli-args.json`, and each one is replayed here against
 * the real `parseCli`.
 *
 * A case's `expect` is either the command object, with `profile: null`
 * standing for `profile: undefined`, or `{ error }` carrying the exact
 * `CliArgError` message.
 *
 * The vector file is regenerated and drift-checked by the "Lean Verify"
 * workflow (`scripts/verification/lean-verify.sh --check`), so it cannot fall
 * behind the model unnoticed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { describe, expect, it } from 'vitest';
import { CliArgError, parseCli } from '../args';

const repoRoot = path.resolve(__dirname, '../../..');

interface CliArgsCase {
  argv: string[];
  expect: Record<string, unknown>;
}

interface VectorFile {
  module: string;
  generator: string;
  lean: string;
  count: number;
  cases: CliArgsCase[];
}

const vectors = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'verification/vectors/cli-args.json'), 'utf8'),
) as VectorFile;

/** The real parser's answer for `argv`, in the vector encoding. */
function observe(argv: string[]): unknown {
  let command: unknown;
  try {
    command = parseCli([...argv]);
  } catch (error) {
    if (error instanceof CliArgError) return { error: error.message };
    // Anything but a CliArgError is a mismatch whatever the model says.
    return { threw: String(error) };
  }
  // JSON has no `undefined`; the model writes `profile: undefined` as null.
  return JSON.parse(JSON.stringify(command, (_key, value) => (value === undefined ? null : value)));
}

describe('cli-args Lean conformance vectors', () => {
  it('carry exactly the cases they declare, enough of them, and no duplicates', () => {
    expect(vectors.module).toBe('cli-args');
    expect(vectors.count).toBe(vectors.cases.length);
    expect(vectors.count).toBeGreaterThan(200);
    // A repeated argv would inflate the count without adding coverage.
    expect(new Set(vectors.cases.map((c) => JSON.stringify(c.argv))).size).toBe(vectors.count);
  });

  it('were generated by the pinned Lean toolchain', () => {
    const toolchain = fs.readFileSync(path.join(repoRoot, 'verification/lean/lean-toolchain'), 'utf8').trim();
    expect(toolchain).toBe(`leanprover/lean4:v${vectors.lean}`);
  });

  it('reach every command and the error path', () => {
    const outcomes = new Set(vectors.cases.map((c) => ('error' in c.expect ? 'error' : String(c.expect.command))));
    expect([...outcomes].sort()).toEqual(
      ['doctor', 'error', 'help', 'profile', 'service', 'sessions', 'setup', 'status', 'version'].sort(),
    );
  });

  it('agree with parseCli on every case', () => {
    let replayed = 0;
    const mismatches: string[] = [];
    for (const c of vectors.cases) {
      const actual = observe(c.argv);
      replayed += 1;
      if (!isDeepStrictEqual(actual, c.expect)) {
        mismatches.push(`${JSON.stringify(c.argv)}: real ${JSON.stringify(actual)}, model ${JSON.stringify(c.expect)}`);
      }
    }
    expect(mismatches).toEqual([]);
    expect(replayed).toBe(vectors.cases.length);
  });
});
