/**
 * Conformance of the snapshot gate with its Lean model.
 *
 * `verification/lean/SomaVerify/FollowupSnapshot/Model.lean` transcribes
 * `parseFollowupQueueSnapshot` (`../followup-queue-store.ts:47-284`) check by
 * check, and `Proofs.lean` proves properties of that transcription: it accepts
 * exactly the snapshots the declarative `ValidSnapshot` describes, it returns
 * its input unchanged, and it answers every input exactly as the gate did
 * before its proof-backed simplification (`ModelOriginal.lean`, whose
 * duplicate-seq check could never fire). Those theorems are about the model;
 * this suite ties the model to the code.
 * `SomaVerify/FollowupSnapshot/Vectors.lean` varies one valid snapshot
 * field by field, adds exhaustive state and `nextSeq` grids, and records what
 * the model does with each document: return it, or throw which message. Every
 * case is replayed here against the real exported function.
 *
 * The vector file is regenerated and drift-checked by the "Lean Verify"
 * workflow (`scripts/verification/lean-verify.sh --check`), so it cannot fall
 * behind the model unnoticed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseFollowupQueueSnapshot } from '../followup-queue-store';

const repoRoot = path.resolve(__dirname, '../../../..');

type Outcome = { ok: true } | { error: string };

interface SnapshotCase {
  name: string;
  input: unknown;
  expect: Outcome;
}

interface VectorFile {
  module: string;
  generator: string;
  lean: string;
  count: number;
  cases: SnapshotCase[];
}

const vectors = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'verification/vectors/followup-snapshot.json'), 'utf8'),
) as VectorFile;

/**
 * JSON cannot write `undefined`, `NaN`, the infinities or `-0`, and the Lean
 * vector writer has integers only, so the generator writes those values (and
 * non-integers) as `{"$js": "<JS literal>"}`. Decoding is literal: `undefined`,
 * or `Number(literal)`, which must not come back NaN unless the literal is
 * `NaN`. Objects are rebuilt with the same keys in the same order, and a
 * decoded `undefined` stays an own property: an explicit `undefined`, the shape
 * `FollowupQueue` itself leaves in memory when it clears a field.
 */
function decode(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(decode);
  if (typeof value !== 'object' || value === null) return value;
  const record = value as Record<string, unknown>;
  if ('$js' in record) {
    const literal = record.$js;
    if (typeof literal !== 'string' || Object.keys(record).length !== 1) {
      throw new Error(`malformed $js marker: ${JSON.stringify(record)}`);
    }
    if (literal === 'undefined') return undefined;
    const number = Number(literal);
    if (Number.isNaN(number) && literal !== 'NaN') throw new Error(`unknown $js literal: ${literal}`);
    return number;
  }
  return Object.fromEntries(Object.entries(record).map(([key, entry]) => [key, decode(entry)]));
}

/** What the real gate does with `input`, in the vector file's terms. */
function outcome(input: unknown): Outcome | { returned: 'a different value' } {
  let result: unknown;
  try {
    result = parseFollowupQueueSnapshot(input);
  } catch (error) {
    return { error: error instanceof Error ? error.message : `non-Error thrown: ${String(error)}` };
  }
  // The gate must hand back the very object it was given (no field lost, none rebuilt).
  return result === input ? { ok: true } : { returned: 'a different value' };
}

describe('followup-snapshot Lean conformance vectors', () => {
  it('carry exactly the cases they declare, enough of them, under distinct names', () => {
    expect(vectors.module).toBe('followup-snapshot');
    expect(vectors.count).toBe(vectors.cases.length);
    expect(vectors.count).toBeGreaterThanOrEqual(200);
    expect(new Set(vectors.cases.map((c) => c.name)).size).toBe(vectors.count);
  });

  it('were generated by the pinned Lean toolchain', () => {
    const toolchain = fs.readFileSync(path.join(repoRoot, 'verification/lean/lean-toolchain'), 'utf8').trim();
    expect(toolchain).toBe(`leanprover/lean4:v${vectors.lean}`);
  });

  it('exercise both outcomes', () => {
    const accepted = vectors.cases.filter((c) => 'ok' in c.expect).length;
    expect(accepted).toBeGreaterThan(0);
    expect(vectors.count - accepted).toBeGreaterThan(0);
  });

  it('decode the non-JSON markers to the values they name', () => {
    expect(decode({ $js: 'undefined' })).toBeUndefined();
    expect(Number.isNaN(decode({ $js: 'NaN' }))).toBe(true);
    expect(decode({ $js: 'Infinity' })).toBe(Number.POSITIVE_INFINITY);
    expect(decode({ $js: '-Infinity' })).toBe(Number.NEGATIVE_INFINITY);
    expect(Object.is(decode({ $js: '-0' }), -0)).toBe(true);
    expect(decode({ $js: '1.5' })).toBe(1.5);
    expect(decode({ $js: '1.0' })).toBe(1);
    const explicit = decode({ steerUuid: { $js: 'undefined' } }) as Record<string, unknown>;
    expect(Object.keys(explicit)).toEqual(['steerUuid']);
    expect(explicit.steerUuid).toBeUndefined();
  });

  it('agree with parseFollowupQueueSnapshot on every case: the same object back, or the same message', () => {
    const mismatches = vectors.cases.flatMap((c) => {
      const actual = outcome(decode(c.input));
      return JSON.stringify(actual) === JSON.stringify(c.expect)
        ? []
        : [`${c.name}: code ${JSON.stringify(actual)}, model ${JSON.stringify(c.expect)}`];
    });
    expect(mismatches).toEqual([]);
  });
});
