/**
 * Conformance of the CCT button-value codec with its Lean model.
 *
 * `verification/lean/SomaVerify/CctActionValue/Model.lean` transcribes
 * `packages/slack/src/cct/action-value.ts`, and the theorems in `Proofs.lean`
 * are about that model. `SomaVerify/CctActionValue/Vectors.lean` records what
 * the model returns on its vector domain (the generator's doc comment lists
 * the input families); this suite asks the real exported functions the same
 * questions: `decodeCctActionValue` and `readCctActionPayload` for every decode
 * case, `encodeCctActionValue` (returned value or thrown message) for every
 * encode case.
 *
 * The model's inputs are strings. What only the TS can be given (non-string
 * values) is pinned by the explicit cases at the end.
 *
 * The vector file is regenerated and drift-checked by the "Lean Verify"
 * workflow (`scripts/verification/lean-verify.sh --check`), so it cannot fall
 * behind the model unnoticed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { describe, expect, it } from 'vitest';
import { type CctCardMode, decodeCctActionValue, encodeCctActionValue, readCctActionPayload } from '../action-value';

const repoRoot = path.resolve(__dirname, '../../../..');

type DecodedExpectation =
  | { kind: 'tagged'; mode: string; payload: string }
  | { kind: 'legacy'; payload: string }
  | { kind: 'invalid'; raw: string };

interface DecodeCase {
  raw: string;
  decode: DecodedExpectation;
  read: string | null;
}

type EncodeOutcome = { ok: string } | { throws: string };

interface EncodeCase {
  mode: string;
  payload: string;
  encode: EncodeOutcome;
}

interface VectorFile {
  module: string;
  generator: string;
  lean: string;
  count: number;
  cases: Array<DecodeCase | EncodeCase>;
}

const vectors = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'verification/vectors/cct-action-value.json'), 'utf8'),
) as VectorFile;

/** Every case has exactly the keys of one of the two kinds. */
const DECODE_KEYS = 'decode,raw,read';
const ENCODE_KEYS = 'encode,mode,payload';

function keysOf(value: object): string {
  return Object.keys(value).sort().join(',');
}

const decodeCases = vectors.cases.filter((c): c is DecodeCase => keysOf(c) === DECODE_KEYS);
const encodeCases = vectors.cases.filter((c): c is EncodeCase => keysOf(c) === ENCODE_KEYS);

/** The interesting characters are invisible and some inputs are 2000 long, so failures name code points. */
function codePoints(text: string): string {
  if (text.length === 0) return '(empty)';
  const points = Array.from(text);
  const shown = points
    .slice(0, 16)
    .map((ch) => `U+${(ch.codePointAt(0) ?? 0).toString(16).toUpperCase().padStart(4, '0')}`)
    .join(' ');
  return points.length > 16 ? `${shown} ... (${text.length} code units)` : shown;
}

function runEncode(mode: string, payload: string): EncodeOutcome {
  try {
    return { ok: encodeCctActionValue({ mode: mode as CctCardMode, payload }) };
  } catch (error) {
    if (!(error instanceof Error)) throw error;
    return { throws: error.message };
  }
}

const ENCODE_ERRORS: Array<[string, string]> = [
  ['unknown mode', 'encodeCctActionValue: unknown mode '],
  ['blank payload', 'encodeCctActionValue: payload must be a non-empty, non-whitespace string'],
  ['over the cap', 'encodeCctActionValue: encoded value '],
];

describe('cct-action-value Lean conformance vectors', () => {
  it('carry exactly the cases they declare, each a decode or an encode case, with no repeats', () => {
    expect(vectors.module).toBe('cct-action-value');
    expect(vectors.count).toBe(vectors.cases.length);
    expect(vectors.count).toBeGreaterThan(200);
    const unknownShapes = vectors.cases.map(keysOf).filter((keys) => keys !== DECODE_KEYS && keys !== ENCODE_KEYS);
    expect(unknownShapes).toEqual([]);
    expect(decodeCases.length + encodeCases.length).toBe(vectors.count);
    // A repeated input would inflate the count without adding coverage.
    expect(new Set(decodeCases.map((c) => c.raw)).size).toBe(decodeCases.length);
    expect(new Set(encodeCases.map((c) => JSON.stringify([c.mode, c.payload]))).size).toBe(encodeCases.length);
  });

  it('were generated by the pinned Lean toolchain', () => {
    const toolchain = fs.readFileSync(path.join(repoRoot, 'verification/lean/lean-toolchain'), 'utf8').trim();
    expect(toolchain).toBe(`leanprover/lean4:v${vectors.lean}`);
  });

  it('reach every outcome of the three functions', () => {
    const seen = new Set<string>();
    for (const c of decodeCases) {
      seen.add(c.decode.kind === 'tagged' ? `decode tagged ${c.decode.mode}` : `decode ${c.decode.kind}`);
      seen.add(c.read === null ? 'read null' : 'read payload');
    }
    for (const c of encodeCases) {
      if ('ok' in c.encode) {
        seen.add('encode ok');
      } else {
        const message = c.encode.throws;
        const match = ENCODE_ERRORS.find(([, prefix]) => message.startsWith(prefix));
        seen.add(`encode throws ${match ? match[0] : message}`);
      }
    }
    expect([...seen].sort()).toEqual(
      [
        'decode tagged admin',
        'decode tagged readonly',
        'decode legacy',
        'decode invalid',
        'read null',
        'read payload',
        'encode ok',
        'encode throws unknown mode',
        'encode throws blank payload',
        'encode throws over the cap',
      ].sort(),
    );
  });

  it('agree with decodeCctActionValue on every decode case', () => {
    const mismatches: string[] = [];
    let replayed = 0;
    for (const c of decodeCases) {
      const actual = decodeCctActionValue(c.raw);
      if (!isDeepStrictEqual(actual, c.decode)) {
        mismatches.push(`[${codePoints(c.raw)}] ts ${JSON.stringify(actual)}, model ${JSON.stringify(c.decode)}`);
      }
      replayed++;
    }
    expect(mismatches).toEqual([]);
    expect(replayed).toBe(decodeCases.length);
  });

  it('agree with readCctActionPayload on every decode case', () => {
    const mismatches: string[] = [];
    let replayed = 0;
    for (const c of decodeCases) {
      const actual = readCctActionPayload(c.raw);
      if (actual !== c.read) {
        mismatches.push(`[${codePoints(c.raw)}] ts ${JSON.stringify(actual)}, model ${JSON.stringify(c.read)}`);
      }
      replayed++;
    }
    expect(mismatches).toEqual([]);
    expect(replayed).toBe(decodeCases.length);
  });

  it('agree with encodeCctActionValue, returned value or thrown message, on every encode case', () => {
    const mismatches: string[] = [];
    let replayed = 0;
    for (const c of encodeCases) {
      const actual = runEncode(c.mode, c.payload);
      if (!isDeepStrictEqual(actual, c.encode)) {
        mismatches.push(
          `mode [${codePoints(c.mode)}] payload [${codePoints(c.payload)}] ts ${JSON.stringify(actual).slice(0, 200)}, model ${JSON.stringify(c.encode).slice(0, 200)}`,
        );
      }
      replayed++;
    }
    expect(mismatches).toEqual([]);
    expect(replayed).toBe(encodeCases.length);
  });
});

describe('cct-action-value outside the model domain (non-string values)', () => {
  const nonStrings: unknown[] = [null, undefined, 42, {}];

  it('decodes every non-string value as invalid, carrying the value itself', () => {
    for (const value of nonStrings) {
      const decoded = decodeCctActionValue(value);
      expect(decoded).toEqual({ kind: 'invalid', raw: value });
      // The same value, not a copy: handlers log it as received.
      if (decoded.kind === 'invalid') expect(decoded.raw).toBe(value);
    }
  });

  it('reads no payload from a non-string value', () => {
    for (const value of nonStrings) {
      expect(readCctActionPayload(value)).toBeNull();
    }
  });

  it('refuses a non-string payload with the blank-payload message', () => {
    for (const payload of nonStrings) {
      expect(() => encodeCctActionValue({ mode: 'admin', payload: payload as string })).toThrow(
        new Error('encodeCctActionValue: payload must be a non-empty, non-whitespace string'),
      );
    }
  });
});
