/**
 * Task 8 RED — atomic profile materialization.
 *
 * The contract under test is byte-level on purpose: `.env` is consumed by
 * `dotenv` and by a launchd service, so "the right keys are in there somewhere"
 * is not a strong enough assertion. Order, spacing, and the trailing newline
 * are all part of the artifact.
 */

import dotenv from 'dotenv';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { type ProfilePaths, profilePaths, type RuntimeInstall } from '../../profile';
import {
  MaterializeProfileError,
  type MaterializeProfileInput,
  materializeProfile,
  type ProfileReceipt,
} from '../materialize';
import { SecretStore } from '../secrets';
import { assertSecretFree } from '../state';

const PACKAGED_CONFIG = JSON.stringify({ ui: { threadheader: { lines: [] } } }, null, 2);
const PACKAGED_PROMPT = '# somawork default system prompt\n';

describe('materializeProfile', () => {
  let home: string;
  let runtimeRoot: string;
  let baseDirectory: string;
  let assetsDir: string;
  let paths: ProfilePaths;
  let runtime: RuntimeInstall;
  const savedUmask = process.umask();

  function input(overrides: Partial<MaterializeProfileInput> = {}): MaterializeProfileInput {
    return {
      profile: 'preview',
      paths,
      runtime,
      baseDirectory,
      llmuxBaseUrl: 'http://localhost:3456',
      slack: { appId: 'A0123456789', teamId: 'T0123456789' },
      defaultConfig: { path: path.join(assetsDir, 'config.default.json') },
      systemPrompt: { path: path.join(assetsDir, 'system.prompt') },
      ...overrides,
    };
  }

  beforeEach(() => {
    home = fs.mkdtempSync(path.join(os.tmpdir(), 'materialize-test-'));
    runtimeRoot = path.join(home, 'runtime', 'somawork-preview');
    baseDirectory = path.join(home, 'Code');
    assetsDir = path.join(home, 'assets');
    fs.mkdirSync(runtimeRoot, { recursive: true });
    fs.mkdirSync(baseDirectory, { recursive: true });
    fs.mkdirSync(assetsDir, { recursive: true });
    fs.writeFileSync(path.join(assetsDir, 'config.default.json'), PACKAGED_CONFIG);
    fs.writeFileSync(path.join(assetsDir, 'system.prompt'), PACKAGED_PROMPT);
    paths = profilePaths(home, 'preview');
    runtime = { profile: 'preview', root: runtimeRoot, version: '1.2.3' };
  });

  afterEach(() => {
    process.umask(savedUmask);
    fs.rmSync(home, { recursive: true, force: true });
  });

  // ---------------------------------------------------------------- artifacts

  it('writes exactly .env, config.json and .system.prompt into the profile config dir', () => {
    materializeProfile(input());
    expect(fs.readdirSync(paths.configDir).sort()).toEqual(['.env', '.system.prompt', 'config.json', 'data']);
  });

  it('produces a byte-stable .env with a fixed line order and a trailing newline', () => {
    const receipt = materializeProfile(input());
    expect(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).toBe(
      [
        '# somawork profile environment - generated by `somawork setup`; edits are overwritten.',
        '# Runtime credentials live in secrets.env (0600) and are never duplicated here.',
        'AUTH_MODE=llmux',
        'ANTHROPIC_BASE_URL=http://localhost:3456',
        'ANTHROPIC_API_KEY=llmux-local',
        `BASE_DIRECTORY=${baseDirectory}`,
        `SOMA_BASE_DIRECTORY=${baseDirectory}`,
        '',
      ].join('\n'),
    );
  });

  it('writes no DATA_DIR line, because the runtime overwrites it with another value', () => {
    // `src/index.ts` re-points `process.env.DATA_DIR` at the env-paths value
    // under SOMA_CONFIG_DIR, so any line here would state a path the running
    // process does not use.
    const receipt = materializeProfile(input());
    expect(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).not.toMatch(/^DATA_DIR=/m);
  });

  it('emits a .env whose every value survives a dotenv round trip', () => {
    const receipt = materializeProfile(input({ baseDirectory: `${home}/Bob's Code` }));
    const parsed = dotenv.parse(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8'));
    expect(parsed.BASE_DIRECTORY).toBe(`${home}/Bob's Code`);
    expect(parsed.SOMA_BASE_DIRECTORY).toBe(`${home}/Bob's Code`);
    expect(parsed.AUTH_MODE).toBe('llmux');
    expect(parsed.ANTHROPIC_BASE_URL).toBe('http://localhost:3456');
  });

  // ------------------------------------------------------------ llmux endpoint

  /**
   * The endpoint is an *input*, not a constant. A second llmux already owning
   * 3456 for the same uid is the ordinary case on a shared machine, and a
   * hardcoded port made the materialized profile point at somebody else's
   * daemon (`llmux env` is what knows the real one).
   */
  it('writes the llmux endpoint it was given rather than a fixed port', () => {
    const receipt = materializeProfile(input({ llmuxBaseUrl: 'http://localhost:13456' }));
    expect(dotenv.parse(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).ANTHROPIC_BASE_URL).toBe(
      'http://localhost:13456',
    );
  });

  it('keeps the .env line order stable for a non-default endpoint', () => {
    const receipt = materializeProfile(input({ llmuxBaseUrl: 'http://127.0.0.1:13456' }));
    expect(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).toBe(
      [
        '# somawork profile environment - generated by `somawork setup`; edits are overwritten.',
        '# Runtime credentials live in secrets.env (0600) and are never duplicated here.',
        'AUTH_MODE=llmux',
        'ANTHROPIC_BASE_URL=http://127.0.0.1:13456',
        'ANTHROPIC_API_KEY=llmux-local',
        `BASE_DIRECTORY=${baseDirectory}`,
        `SOMA_BASE_DIRECTORY=${baseDirectory}`,
        '',
      ].join('\n'),
    );
  });

  it('writes the validated origin, not the caller string, for a trailing slash', () => {
    const receipt = materializeProfile(input({ llmuxBaseUrl: 'http://localhost:13456/' }));
    expect(dotenv.parse(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).ANTHROPIC_BASE_URL).toBe(
      'http://localhost:13456',
    );
  });

  it.each([
    ['a remote https host', 'https://evil.example.com'],
    ['a lookalike registrable domain', 'http://localhost.evil.example:3456'],
    ['a remote host on the expected port', 'http://10.0.0.5:3456'],
    ['embedded userinfo', 'http://user:pass@localhost:3456'],
    ['a path', 'http://localhost:3456/exfil'],
    ['a query string', 'http://localhost:3456/?to=evil.example'],
    ['a non-http scheme', 'file:///etc/passwd'],
    ['an unparseable value', 'not a url'],
    ['an out-of-range port', 'http://localhost:99999'],
    ['an empty string', ''],
  ])('refuses %s and writes nothing', (_label, badUrl) => {
    expect(() => materializeProfile(input({ llmuxBaseUrl: badUrl }))).toThrow(MaterializeProfileError);
    expect(fs.existsSync(path.join(paths.configDir, '.env'))).toBe(false);
  });

  it('refuses a missing endpoint rather than falling back to a default port', () => {
    expect(() => materializeProfile(input({ llmuxBaseUrl: undefined as unknown as string }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('names no rejected endpoint value in its refusal', () => {
    const bad = 'http://exfil.evil.example:3456';
    const error = (() => {
      try {
        materializeProfile(input({ llmuxBaseUrl: bad }));
        return null;
      } catch (err) {
        return err as Error;
      }
    })();
    expect(error).toBeInstanceOf(MaterializeProfileError);
    expect(error?.message).not.toContain(bad);
    expect(error?.message).not.toContain('evil');
  });

  it('writes the packaged system prompt verbatim rather than an empty placeholder', () => {
    const receipt = materializeProfile(input());
    expect(fs.readFileSync(receipt.promptFile, 'utf-8')).toBe(PACKAGED_PROMPT);
  });

  it('writes config.json as stable JSON that parses back to the packaged defaults', () => {
    const receipt = materializeProfile(input());
    const text = fs.readFileSync(receipt.configFile, 'utf-8');
    expect(text.endsWith('\n')).toBe(true);
    expect(JSON.parse(text)).toEqual(JSON.parse(PACKAGED_CONFIG));
  });

  it('accepts packaged assets supplied as content instead of a path', () => {
    const receipt = materializeProfile(
      input({ defaultConfig: { content: '{"ui":{}}' }, systemPrompt: { content: 'hi\n' } }),
    );
    expect(fs.readFileSync(receipt.promptFile, 'utf-8')).toBe('hi\n');
    expect(JSON.parse(fs.readFileSync(receipt.configFile, 'utf-8'))).toEqual({ ui: {} });
  });

  it('generates a config.json with no unresolved ${VAR} placeholders', () => {
    const receipt = materializeProfile(input());
    expect(fs.readFileSync(receipt.configFile, 'utf-8')).not.toMatch(/\$\{/);
  });

  // -------------------------------------------------------------------- modes

  it('writes 0600 files and 0700 directories even under a permissive umask', () => {
    // `umask` is process-global. Vitest's forks pool runs one file at a time
    // per worker, so no sibling file can observe this — but the window is
    // closed in a `finally` rather than in `afterEach` so it cannot outlive
    // this call even if an assertion below throws.
    let receipt: ProfileReceipt;
    process.umask(0o000);
    try {
      receipt = materializeProfile(input());
    } finally {
      process.umask(savedUmask);
    }
    for (const file of [receipt.runtimeEnvFile, receipt.configFile, receipt.promptFile]) {
      expect(fs.statSync(file).mode & 0o777).toBe(0o600);
    }
    for (const dir of [receipt.configDir, receipt.dataDir, receipt.stateDir, receipt.runtimeDataDir]) {
      expect(fs.statSync(dir).mode & 0o777).toBe(0o700);
    }
  });

  it('tightens a pre-existing 0755 profile config directory to 0700', () => {
    fs.mkdirSync(paths.configDir, { recursive: true, mode: 0o755 });
    fs.chmodSync(paths.configDir, 0o755);
    const receipt = materializeProfile(input());
    expect(fs.statSync(receipt.configDir).mode & 0o777).toBe(0o700);
  });

  // ------------------------------------------------------------------- backup

  it('keeps the previous contents as .bak when overwriting an existing profile', () => {
    materializeProfile(input());
    fs.writeFileSync(path.join(paths.configDir, '.system.prompt'), 'operator edit\n');
    materializeProfile(input());
    expect(fs.readFileSync(path.join(paths.configDir, '.system.prompt.bak'), 'utf-8')).toBe('operator edit\n');
  });

  // --------------------------------------------------------------- idempotence

  it('is idempotent: a second run reproduces byte-identical artifacts and receipt', () => {
    const first = materializeProfile(input());
    const before = [first.runtimeEnvFile, first.configFile, first.promptFile].map((f) => fs.readFileSync(f, 'utf-8'));
    const second = materializeProfile(input());
    const after = [second.runtimeEnvFile, second.configFile, second.promptFile].map((f) => fs.readFileSync(f, 'utf-8'));
    expect(after).toEqual(before);
    expect(second).toEqual(first);
  });

  // ------------------------------------------------------------- isolation

  it('keeps preview and production artifacts in non-colliding locations', () => {
    const previewReceipt = materializeProfile(input());
    const productionPaths = profilePaths(home, 'production');
    const productionReceipt = materializeProfile(
      input({
        profile: 'production',
        paths: productionPaths,
        runtime: { profile: 'production', root: runtimeRoot, version: '1.2.3' },
      }),
    );

    const previewFiles = [previewReceipt.runtimeEnvFile, previewReceipt.configFile, previewReceipt.promptFile];
    const productionFiles = [
      productionReceipt.runtimeEnvFile,
      productionReceipt.configFile,
      productionReceipt.promptFile,
    ];
    expect(previewFiles.some((f) => productionFiles.includes(f))).toBe(false);
    expect(previewReceipt.dataDir).not.toBe(productionReceipt.dataDir);
    expect(previewReceipt.stateDir).not.toBe(productionReceipt.stateDir);
    expect(fs.existsSync(previewReceipt.runtimeEnvFile)).toBe(true);
    expect(fs.existsSync(productionReceipt.runtimeEnvFile)).toBe(true);
  });

  // -------------------------------------------------------------- validation

  it('refuses a relative profile config directory', () => {
    expect(() => materializeProfile(input({ paths: { ...paths, configDir: 'relative/config' } }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('refuses a relative base directory', () => {
    expect(() => materializeProfile(input({ baseDirectory: './Code' }))).toThrow(MaterializeProfileError);
  });

  it('refuses a relative runtime root', () => {
    expect(() => materializeProfile(input({ runtime: { ...runtime, root: 'runtime' } }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('refuses a runtime install whose profile does not match the requested profile', () => {
    expect(() => materializeProfile(input({ runtime: { ...runtime, profile: 'production' } }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('refuses to write when a config-dir ancestor is a symlink', () => {
    const real = path.join(home, 'real-config-parent');
    fs.mkdirSync(real, { recursive: true });
    const linked = path.join(home, 'linked-config-parent');
    fs.symlinkSync(real, linked);
    expect(() => materializeProfile(input({ paths: { ...paths, configDir: path.join(linked, 'preview') } }))).toThrow();
  });

  it('refuses to materialize into the immutable runtime root', () => {
    expect(() =>
      materializeProfile(input({ paths: { ...paths, configDir: path.join(runtimeRoot, 'config') } })),
    ).toThrow(MaterializeProfileError);
    expect(fs.readdirSync(runtimeRoot)).toEqual([]);
  });

  it('refuses to materialize into a Homebrew Cellar path', () => {
    const cellar = path.join(home, 'opt', 'homebrew', 'Cellar', 'somawork', '1.2.3', 'config');
    expect(() => materializeProfile(input({ paths: { ...paths, configDir: cellar } }))).toThrow(
      MaterializeProfileError,
    );
    expect(fs.existsSync(cellar)).toBe(false);
  });

  it('accepts an apostrophe in a workspace path, which dotenv round-trips correctly', () => {
    const withApostrophe = path.join(home, "Bob's Code");
    fs.mkdirSync(withApostrophe, { recursive: true });
    const receipt = materializeProfile(input({ baseDirectory: withApostrophe }));
    expect(dotenv.parse(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).BASE_DIRECTORY).toBe(withApostrophe);
  });

  it('accepts an embedded double quote, which dotenv also round-trips correctly', () => {
    const withQuote = path.join(home, 'say"hi');
    const receipt = materializeProfile(input({ baseDirectory: withQuote }));
    expect(dotenv.parse(fs.readFileSync(receipt.runtimeEnvFile, 'utf-8')).BASE_DIRECTORY).toBe(withQuote);
  });

  it('refuses a value wrapped in matching single quotes, which dotenv would strip', () => {
    expect(() => materializeProfile(input({ baseDirectory: `'${home}/quoted'` }))).toThrow(MaterializeProfileError);
  });

  it('refuses a value wrapped in matching double quotes, which dotenv would strip', () => {
    expect(() => materializeProfile(input({ baseDirectory: `"${home}/quoted"` }))).toThrow(MaterializeProfileError);
  });

  it('refuses an env value that dotenv would silently truncate at a "#"', () => {
    expect(() => materializeProfile(input({ baseDirectory: `${home}/Co#de` }))).toThrow(MaterializeProfileError);
  });

  it('refuses an env value containing a newline that would forge a second assignment', () => {
    expect(() => materializeProfile(input({ baseDirectory: `${home}/Code\nSLACK_BOT_TOKEN=x` }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('refuses a credential-shaped Slack identifier instead of persisting it', () => {
    expect(() =>
      materializeProfile(input({ slack: { appId: 'xoxb-1234567890-abcdef', teamId: 'T0123456789' } })),
    ).toThrow(MaterializeProfileError);
  });

  it('fails loudly when the packaged system prompt is unavailable', () => {
    expect(() => materializeProfile(input({ systemPrompt: { path: path.join(assetsDir, 'missing.prompt') } }))).toThrow(
      MaterializeProfileError,
    );
    expect(fs.existsSync(path.join(paths.configDir, '.system.prompt'))).toBe(false);
  });

  it('fails loudly when the packaged system prompt is empty rather than writing a silent empty file', () => {
    expect(() => materializeProfile(input({ systemPrompt: { content: '   \n' } }))).toThrow(MaterializeProfileError);
    expect(fs.existsSync(path.join(paths.configDir, '.system.prompt'))).toBe(false);
  });

  it('fails loudly when the packaged default config is unavailable', () => {
    expect(() => materializeProfile(input({ defaultConfig: { path: path.join(assetsDir, 'missing.json') } }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('refuses a packaged default config with no ui object, which the runtime would seed and rewrite', () => {
    // `loadConfig` seeds DEFAULT_UI_SURFACES and REWRITES config.json when the
    // key is absent — at the ambient umask, undoing this module's 0600 write.
    expect(() => materializeProfile(input({ defaultConfig: { content: '{}' } }))).toThrow(MaterializeProfileError);
  });

  it('refuses a packaged default config whose ui is not an object', () => {
    expect(() => materializeProfile(input({ defaultConfig: { content: '{"ui":[]}' } }))).toThrow(
      MaterializeProfileError,
    );
    expect(() => materializeProfile(input({ defaultConfig: { content: '{"ui":null}' } }))).toThrow(
      MaterializeProfileError,
    );
  });

  it('fails loudly when the packaged default config is not a JSON object', () => {
    expect(() => materializeProfile(input({ defaultConfig: { content: '[1,2,3]' } }))).toThrow(MaterializeProfileError);
  });

  it('validates every artifact before writing any of them', () => {
    // A bad prompt is discovered last; nothing may be left half-materialized.
    expect(() => materializeProfile(input({ systemPrompt: { content: '' } }))).toThrow(MaterializeProfileError);
    expect(fs.existsSync(paths.configDir)).toBe(false);
  });

  // ------------------------------------------------------------------ receipt

  it('returns a receipt that clears the setup-state secret gate', () => {
    const receipt: ProfileReceipt = materializeProfile(input());
    expect(() => assertSecretFree(receipt)).not.toThrow();
  });

  it('returns a receipt naming both env files the service must load, secrets last', () => {
    const receipt = materializeProfile(input());
    expect(receipt.serviceEnvFiles).toEqual([receipt.runtimeEnvFile, paths.secretsFile]);
  });

  it('returns non-secret paths and identifiers only', () => {
    const receipt = materializeProfile(input());
    expect(receipt).toEqual({
      profile: 'preview',
      appId: 'A0123456789',
      teamId: 'T0123456789',
      baseDirectory,
      configDir: paths.configDir,
      configFile: path.join(paths.configDir, 'config.json'),
      dataDir: paths.dataDir,
      promptFile: path.join(paths.configDir, '.system.prompt'),
      runtimeDataDir: path.join(paths.configDir, 'data'),
      runtimeEnvFile: path.join(paths.configDir, '.env'),
      runtimeRoot,
      runtimeVersion: '1.2.3',
      serviceEnvFiles: [path.join(paths.configDir, '.env'), paths.secretsFile],
      stateDir: paths.stateDir,
    });
  });

  // ------------------------------------------------------------------ secrets

  it('never copies a Slack runtime token into any materialized file', () => {
    const store = new SecretStore({ secretsFile: paths.secretsFile });
    store.write({ SLACK_BOT_TOKEN: 'xoxb-sentinel-bot', SLACK_APP_TOKEN: 'xapp-sentinel-app' });
    const receipt = materializeProfile(input());
    for (const file of [receipt.runtimeEnvFile, receipt.configFile, receipt.promptFile]) {
      const text = fs.readFileSync(file, 'utf-8');
      expect(text).not.toContain('xoxb-sentinel-bot');
      expect(text).not.toContain('xapp-sentinel-app');
      expect(text).not.toContain('SLACK_BOT_TOKEN');
      expect(text).not.toContain('SLACK_APP_TOKEN');
      expect(text).not.toContain('SLACK_SIGNING_SECRET');
    }
  });

  it('leaves an already-written secrets.env untouched', () => {
    const store = new SecretStore({ secretsFile: paths.secretsFile });
    store.write({ SLACK_BOT_TOKEN: 'xoxb-sentinel-bot' });
    const before = fs.readFileSync(paths.secretsFile, 'utf-8');
    materializeProfile(input());
    expect(fs.readFileSync(paths.secretsFile, 'utf-8')).toBe(before);
    expect(fs.statSync(paths.secretsFile).mode & 0o777).toBe(0o600);
  });
});
