/**
 * ReleaseNotifier — Posts version info and release notes to Slack on startup.
 * Reads dist/version.json (generated by CI) and posts to DEFAULT_UPDATE_CHANNEL.
 */

import { WebClient } from '@slack/web-api';
import { readFileSync, existsSync } from 'fs';
import path from 'path';
import { Logger } from './logger';

const logger = new Logger('ReleaseNotifier');

export interface VersionInfo {
  version: string;
  previousVersion: string;
  tag: string;
  previousTag: string;
  commitHash: string;
  commitHashShort: string;
  commitTime: string;
  branch: string;
  buildTime: string;
  releaseNotes: string;
}

function loadVersionInfo(): VersionInfo | null {
  const versionPath = path.join(process.cwd(), 'dist', 'version.json');
  if (!existsSync(versionPath)) {
    logger.debug('No dist/version.json found, skipping release notification');
    return null;
  }

  try {
    const content = readFileSync(versionPath, 'utf-8');
    return JSON.parse(content) as VersionInfo;
  } catch (error) {
    logger.warn('Failed to read version.json', { error: (error as Error).message });
    return null;
  }
}

function resolveChannel(client: WebClient, channelName: string): Promise<string | null> {
  // If it's already an ID (starts with C), return as-is
  if (channelName.startsWith('C')) return Promise.resolve(channelName);

  // Strip # prefix
  const name = channelName.replace(/^#/, '');

  return client.conversations.list({
    types: 'public_channel',
    limit: 1000,
  }).then(result => {
    const channel = result.channels?.find(ch => ch.name === name);
    return channel?.id || null;
  }).catch(error => {
    logger.warn('Failed to resolve channel name', { channelName, error: (error as Error).message });
    return null;
  });
}

export function formatTimestamp(isoTime: string): string {
  try {
    const date = new Date(isoTime);
    return `<!date^${Math.floor(date.getTime() / 1000)}^{date_short_pretty} {time}|${isoTime}>`;
  } catch {
    return isoTime;
  }
}

/**
 * Send release notification to the configured channel.
 * Call after app.start() succeeds.
 */
export async function notifyRelease(client: WebClient): Promise<void> {
  const channelConfig = process.env.DEFAULT_UPDATE_CHANNEL;
  if (!channelConfig) {
    logger.debug('DEFAULT_UPDATE_CHANNEL not set, skipping release notification');
    return;
  }

  const versionInfo = loadVersionInfo();
  if (!versionInfo) return;

  const channelId = await resolveChannel(client, channelConfig);
  if (!channelId) {
    logger.warn('Could not resolve DEFAULT_UPDATE_CHANNEL', { channelConfig });
    return;
  }

  const isUpgrade = versionInfo.previousVersion !== '0.0.0' &&
    versionInfo.version !== versionInfo.previousVersion;

  const headerText = isUpgrade
    ? `🚀 *v${versionInfo.version}* 배포 완료  _(v${versionInfo.previousVersion} → v${versionInfo.version})_`
    : `🚀 *v${versionInfo.version}* 배포 완료`;

  const blocks: any[] = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: `🚀 soma-work v${versionInfo.version} 배포`,
        emoji: true,
      },
    },
    {
      type: 'section',
      fields: [
        {
          type: 'mrkdwn',
          text: `*버전*\n\`${versionInfo.tag}\``,
        },
        {
          type: 'mrkdwn',
          text: `*브랜치*\n\`${versionInfo.branch}\``,
        },
        {
          type: 'mrkdwn',
          text: `*커밋*\n\`${versionInfo.commitHashShort}\``,
        },
        {
          type: 'mrkdwn',
          text: `*커밋 시간*\n${formatTimestamp(versionInfo.commitTime)}`,
        },
      ],
    },
  ];

  // Release notes section
  if (versionInfo.releaseNotes) {
    blocks.push(
      { type: 'divider' },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*📋 변경 사항*${isUpgrade ? ` _(${versionInfo.previousTag} → ${versionInfo.tag})_` : ''}\n\n${versionInfo.releaseNotes}`,
        },
      },
    );
  }

  // Footer
  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: `빌드: ${formatTimestamp(versionInfo.buildTime)} | 커밋: \`${versionInfo.commitHash.substring(0, 12)}\``,
      },
    ],
  });

  try {
    await client.chat.postMessage({
      channel: channelId,
      text: headerText,
      blocks,
      unfurl_links: false,
      unfurl_media: false,
    });
    logger.info('Release notification sent', {
      channel: channelConfig,
      version: versionInfo.version,
    });
  } catch (error) {
    logger.warn('Failed to send release notification', {
      error: (error as Error).message,
      channel: channelConfig,
    });
  }
}

/**
 * Get the current version info (for status display or other uses).
 */
export function getVersionInfo(): VersionInfo | null {
  return loadVersionInfo();
}
